### ISSUE TITLE
[Feat] +버튼 누르면 요청 전송 화면으로

### ISSUE THREAD

**Issue by JUNY0110** [DeveloperAcademy-POSTECH/MC3-Team8-FOX#14]
## 구현할 요소 
* +버튼(추가버튼) 생성
* 네비게이션 전환 기능 추가

## 구현 계획 
* 이슈와 관련된 학습 방법이나 구현 계획을 작성합니다. 

## 체크리스트 
- [ ] 버튼 만들기 

## 기타 
* 참고한 레퍼런스를 첨부합니다.

**Comment by yungahui** [comment]
26b92425fd2dcb91ed31200c0ddf37775e1f9df4
뷰 연결 후 커밋 완료
